server:  
  port: ${PORT:3333}

spring: 
  datasource:
      url: jdbc:mysql://localhost:3306/account
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
#  zipkin:
#    base-url: http://zipkin:9411/
#    enabled: true
    
    


eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname:  localhost #customerservice
           
ribbon:
  eureka:
    enabled: true